#!/bin/bash

USER="gubuntum"

for i in $(seq 100 110); do
    IP="192.168.0.$i"
    echo -n "checking ip.$i"
    
    if ping -c 1 -W 1 "$IP" &>/dev/null; then
        echo "connecting!"
        ssh "$USER@$IP"
        exit 0
    else
        echo "no answer"
    fi
done

echo "not found"
